### ISSUE TITLE
[Build] 'make env' throws an error when trying to execute ./activate

### ISSUE THREAD

**Issue by piyushhari** [ignotus-peverell/nash#20]
```
$ make env
.
.

./activate
make: ./activate: Permission denied
make: *** [env] Error 1
```

Steps to Reproduce:
1. Fresh checkout of the repo.
2. Ensure 'activate' symbolic link and 'nashenv' directory do not exist. If they do, delete.
3. Execute 'make env'

**Comment by piyushhari** [comment]
Root cause :
./activate is a symlink and has execute permissions but the executable it is linking to does not

`8 lrwxr-xr-x   1 piyush  staff    20 Apr  4 11:22 activate -> nashenv/bin/activate`

`8 -rw-r--r--  1 piyush  staff  2090 Apr  4 11:21 nashenv/bin/activate`

The fix is to do a `chmod +x` on the linked executable. I will fix it in my branch and send a pull.

**Comment by piyushhari** [comment]
Actually, we cannot execute 'source' in MakeFile. So, we should simply exclude the steps to invoke 'activate' from the MakeFile. It needs to be manually invoked and the README.md has the documentation already on doing so.

**Comment by ignotus-peverell** [comment]
Removed offending line from Makefile.
